repository: Intangible-pg18/intangible_pg18.github.io
# Personal info
name: Prateek Shukla
title: B.Tech Electronics and Computer Engineering
Interest : Data Science & Machine Learning
email: ps4434@srmist.edu.in

phone: "+91 9580646510"
website: intangible_pg18.github.io

darkmode: false

# Social links
github_username:  Intangible-pg18
linkedin_username: prateek-shukla-34267718b
#use international format
whatsapp_number: "919580646510"

#Comment out to disable github stats
githubstats: True

# Additional icon links
#additional_links:P
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
favicon: images/fav.ico
about_profile_image: images/1586960384677.jpg
about_content: | # this will include new lines to allow paragraphs
  A B.Tech student with keen interest in <mark>Data Science</mark> and <mark>Machine Learning</mark>.
  With only one goal in life- to combine the power of Artificial Intelligence and Computer Vision to upscale the production of self driven transportation and visual security.

  <b>I'm currently working on</b>: <mark>Full Stack Web Development</mark> skills

  <b>Stuff I'm good with</b>:
  - <mark>Languages</mark> : <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg" alt="python" width="40" height="40"/> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/cplusplus/cplusplus-original.svg" alt="cplusplus" width="40" height="40"/> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="40" height="40"/> <img align="left" alt="T-SQL" width="26px" src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/sql/sql.png" />  <img src="https://www.vectorlogo.zone/logos/gnu_bash/gnu_bash-icon.svg" alt="bash" width="40" height="40"/>

  - <mark>Machine Learning</mark> : <img src="https://upload.wikimedia.org/wikipedia/commons/0/05/Scikit_learn_logo_small.svg" alt="scikit_learn" width="40" height="40"/>  <img src="https://www.vectorlogo.zone/logos/numpy/numpy-ar21.svg" alt="numpy" width="40" height="40"/> <img src="https://en.wikipedia.org/wiki/Pandas_(software)#/media/File:Pandas_logo.svg" alt="pandas" width="40" height="40"/> <img src="https://en.wikipedia.org/wiki/Matplotlib#/media/File:Matplotlib_logo.svg" alt="matplotlib" width="40" height="40"/>
  
  - <mark>DevOps</mark> : <img src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/git/git.png" alt="git" width="40" height="40"/>  <img src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/terminal/terminal.png" alt="linux-terminal" width="40" height="40"/>
  Feel free to reach out on my [LinkedIn](https://www.linkedin.com/in/prateek-shukla-34267718b/) anytime. Always ready to talk <b>Tech</b>.


# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme : sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed
  load_paths:
        - _sass
        - node_modules


plugins:
  - jekyll-seo-tag

color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

markdown: kramdown
permalink: pretty

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  "docs/",
  "README.md",
  ]
